
<link rel="stylesheet" href="Public/css/list-all.css">
<script src="https://kit.fontawesome.com/d6818a8498.js" crossorigin="anonymous"></script>

<div class="tieude">
    <h2>SHOP ALL</h2>
</div>
<div class="container">
    <div class="filter expand">
        <h2>Filter by </h2>
        <hr>
        <div class="conlection opti">
           
            <div>Collection <i class="fas fa-plus btn btn-collect"></i></div>
            <div class="sub-collection sub">
                <div class="all" ><a href="<?php echo base_path ?>?ct=products&act=list-all">All</a></div>
                <div class="hand-bag" ><a href="<?php echo base_path ?>?ct=products&act=filter&category=tuisach">bag</a></div>
                <div class="dong-ho"><a href="<?php echo base_path ?>?ct=products&act=filter&category=vi">wallet</a></div>
                <div class="vi"><a href="<?php echo base_path ?>?ct=products&act=filter&category=daylung">leather belts</a></div>
                <div class="vi"><a href="<?php echo base_path ?>?ct=products&act=filter&category=opdt">phone covers</a></div>

            </div>
        </div>
        <hr>
        
        <div class="price opti">
        
            <div>Price <i class="fas fa-plus btn btn-price" ></i></div>
            
            <div class="sub-price sub">
                <div class="all"><a href="<?php echo base_path ?>?ct=products&act=list-all">All</a></div>
                <div class="hand-bag" ><a href="<?php echo base_path ?>?ct=products&act=filter&category=tuisach">0 - $50</a></div>
                <div class="hand-bag" ><a href="<?php echo base_path ?>?ct=products&act=filter&category=tuisach">$20-$50</a></div>
                <div class="hand-bag" ><a href="<?php echo base_path ?>?ct=products&act=filter&category=tuisach">$50-$100</a></div>
                <div class="hand-bag" ><a href="<?php echo base_path ?>?ct=products&act=filter&category=tuisach"><$100</a></div>
               
            </div>
        </div>
        <hr>

        <div class="model opti">
           
            <div >Model<i class="fas fa-plus btn"></i></div>
           
        </div>
        <hr>
        <div class="size opti">
           
            <div>Size<i class="fas fa-plus btn"></i></div>
            
        </div>
        <hr>
    </div>


    <div class="list-prod">
     
        <?php 


            foreach ($this->dataView['list-prod'] as $row ) {
                $price  = number_format($row['price']);
                echo "<div class='items' >";
                    

                    echo "<a href='' class='avt' >" . '<img src="'. base_path .'/Public/files/products/' . $row['uid'] . ".webp".'"/>' . '</a>';
                    
                    echo "<p class='gia'>" ."$".$price . '</p>';
                    echo "<a href='". base_path ."?ct=products&act=add-cart&id={$row['uid']}'><div  class='addToC'>" . "add to cart" . '</div></a>';
                

                    echo "<div class='options'>";  
                        echo "<p>" . $row['name'] . '</p>';
                        
                    echo "</div>";
                

                
                echo "</div>";
            }



            ?> 

    </div>
</div>
<hr>


<script src="Public/js/list-all.js"></script>

