
<link rel="stylesheet" href="Public/css/list-all.css">

<div class="tieude">
    <h2>SHOP ALL</h2>
</div>
<div class="container">
    <div class="filter expand">
        <h2 >Filter by</h2>
        <hr>
        <div class="conlection opti">
           
            <div >Collection</div>
            <div class="sub-collection sub">
                <div class="all"><p>All</p></div>
                <div class="hand-bag"><p>Hand Bag</p></div>
                <div class="dong-ho"><p>Dong Ho</p></div>
                <div class="vi"><p>Vi</p></div>

            </div>
        </div>
        <hr>
        
        <div class="price opti">
            
            <div >Price</div>
            <div class="sub-price">
            </div>
        </div>
        <hr>

        <div class="model opti">
           
            <div >Model</div>
           
        </div>
        <hr>
        <div class="size opti">
           
            <div>Size</div>
            
        </div>
        <hr>
    </div>


    <div class="list-prod">
        <?php
            // echo '<pre>';
            //     print_r($this->dataView);
            // echo '</pre>'; 

            foreach ($this->dataView['list-prod'] as $row ) {
                echo "<li class='items'>";

                    echo "<a href=''>" . '<img width="100" src="'. base_path .'/Public/files/products/' . $row['id'] . ".webp".'"/>' . '</a>';
                    echo "<div class='options'>";
                    echo "<br><a href='#'>" . $row['name'] . '</a>';
                    echo "<br><a href='". base_path ."?ct=products&act=add-cart&id={$row['id']}'>" . "add to cart" . '</a>';
                    echo "<br><p>" . $row['price'] . '</p>';
                    echo "</div>";
                echo "</li>";
            }
        ?>

    </div>
</div>


<script src="Public/js/list-all.js"></script>

