
<link rel="stylesheet" href="Public/css/view-cart.css">
<h2>Cart</h2>


<div class="container">
    <div class="container-items">
        <?php
            if (!empty($this->dataView['list_prod'])) {   
                $sumAll = 0;
                    foreach ($this->dataView['list_prod'] as $row ) {
                                
                        $id_prod = $row['uid'];
                        $amount = $_SESSION['cart'][$id_prod];
                        $price  = number_format($row['price']);
                        $sum = $amount *$row['price'];
                        $sumAll += $sum;
                        $sum = number_format($sum);
                        echo"<div class='items'>
                                        
                                <div class='imgs'> <img src='" . base_path . "/Public/files/products/{$row['uid']}.webp' width='100'>   </div> 
                                <div class='name'>{$row['name']}</div>
                                <div class='price'>{$price}</div>
                                <a  class='remove' href='/practive/online-store/?ct=products&act=remove&id=$id_prod'>remove</a>
                                          
                                <div class='amount'>
                                    <a href='/practive/online-store/?ct=products&act=red-prod&id=$id_prod'><i class='fas fa-minus' ></i></a>
                                    {$amount}
                                    <a href='/practive/online-store/?ct=products&act=inc-prod&id=$id_prod'><i class='fas fa-plus' ></i></a>

                                </div> 
                                            
                                
                            </div>";
                };
                $sumAll = number_format($sumAll);
                echo "
                <div class='compute'>
                        <div class='tamtinh'>
                            <div>
                                <h3>Tam tinh</h3>
                            </div>
                            <div class='gia'>
                                <p>{$sumAll} </p>
                            </div>
                                    
                        </div>
                        <hr>
                        <div class='tongtien tamtinh'>
                            <div>
                                <h3>thành Tiền</h3>
                            </div>
                            <div class='gia'>
                                <p>$sumAll</p>
                                <i>(da bao gom phi VAT neu co)</i>
                            </div>
                            
                          
                                                        
                        
                        
                        </div>
                        <div class='pay'>
                           <a href='" . base_path . "?ct=products&act=to-pay'><input type='button' value='tiến hành thanh toán'></a>
                         
                        </div>
                
                </div>";



           
            }else{
                echo "gio hang cua ban dang trong";




            }         

            
                
        ?>  
    </div>
    


</div>
<script src="https://kit.fontawesome.com/d6818a8498.js" crossorigin="anonymous"></script>
