<link rel="stylesheet" href="Public/css/edit.css">
        <div class="container">   
            
            <a href="<?php echo base_path?>?ct=admin&act=add-prod">add product</a>  
            <table class="table table-striped" id="table">
                <h2>Edit</h2>
                <thead>
                    <tr>
                    <th scope="col">#id</th>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Catetory</th>
                    <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    
                    <?php 
                        // echo "<pre>";
                        // print_r($this->dataView);
                        // echo "</pre>";

                        foreach ($this->dataView['list-prod'] as $row ) {
                            $price  = number_format($row['price']);
                            
                            echo '  <tr>
                                    <th scope="row">'.$row['uid'].'</th>
                                    <td><img src="'. base_path .'/Public/files/products/' . $row['uid'] . ".webp".'" width="100px"/></td>
                                    <td><p>'.$row['name'].'</p></td>
                                    <td><p>' ."$".$price . '</p></td>
                                    <td><p>'.$row['type'].'</p></td>
                                    <td>
                                        <a  href=><i class="fas fa-pencil-alt"></i></a>
                                        <a href='.base_path.'?ct=admin&act=delete&id='.$row['id'].'><i class="far fa-trash-alt"></i></a>
                                        
                                    </td>
                                    </tr>';
                                    // href='" . base_path . "?ct=products&act=view-cart'
                            
                        }
                    ?> 
                </tbody>
            </table>
        </div>
    <script>
        $(document).ready( function () {
            $('#table').DataTable();
        } );
    </script>
