<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="View/index/css/style.css">
    <!-- //carousel -->
    
    <link rel="stylesheet" href="View/index/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="View/index/owlcarousel/assets/owl.theme.default.min.css">    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="View/index/owlcarousel/owl.carousel.min.js"></script>
    

    <title>Document</title>
</head>
<body>
    


    <div class="app">

        <div class="cardList">
            <button class="cardList__btn btn btn--left">
                <div class="icon">
                    <svg>
                        <use xlink:href="#arrow-left"></use>
                    </svg>
                </div>
            </button>

            <div class="cards__wrapper">
                <div class="card current--card">
                    <div class="card__image">
                        <img src="View/index/images/slide01.webp" alt="" />
                    </div>
                </div>

                <div class="card next--card">
                    <div class="card__image">
                        <img src="View/index/images/slide02.webp" alt="" />
                    </div>
                </div>

                <div class="card previous--card">
                    <div class="card__image">
                        <img src="View/index/images/slide03.webp" alt="" />
                    </div>
                </div>
            </div>

            <button class="cardList__btn btn btn--right">
                <div class="icon">
                    <svg>
                        <use xlink:href="#arrow-right"></use>
                    </svg>
                </div>
            </button>
        </div>

        <div class="infoList">
            <div class="info__wrapper">
                <div class="info current--info">
                    <h1 class="text name">FANNY PACK</h1>
                    <h4 class="text location">UK</h4>
                    <p class="text description">Family Owned</p>
                </div>

                <div class="info next--info">
                    <h1 class="text name">MINI LEATHER GOODS</h1>
                    <h4 class="text location">USA</h4>
                    <p class="text description">Created in the USA</p>
                </div>

                <div class="info previous--info">
                    <h1 class="text name"> LEATHER BELTS</h1>
                    <h4 class="text location">France</h4>
                    <p class="text description">Hand Crafted</p>
                </div>
            </div>
        </div>


        <div class="app__bg">
            <div class="app__bg__image current--image">
                <img src="View/index/images/slide03.webp" alt="" />
            </div>
            <div class="app__bg__image next--image">
                <img src="View/index/images/slide02.webp" alt="" />
            </div>
            <div class="app__bg__image previous--image">
                <img src="View/index/images/slide01.webp"  alt="" />
            </div>
        </div>
    </div>

    <div class="loading__wrapper">
        <div class="loader--text">Loading...</div>
        <div class="loader">
            <span></span>
        </div>
    </div>


    <svg class="icons" style="display: none;">
        <symbol id="arrow-left" xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'>
            <polyline points='328 112 184 256 328 400'
                style='fill:none;stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px' />
        </symbol>
        <symbol id="arrow-right" xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'>
            <polyline points='184 112 328 256 184 400'
                style='fill:none;stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px' />
        </symbol>
    </svg>


    <script src="View/index/js/imagesLoaded.pkgd.min.js"></script>
    <script src="View/index/js/softripple.min.js"></script>
    <script src="View/index/js/gsap.min.js"></script>
    <script src="View/index/js/script.js"></script> 


<div class="best-seller">
    <h2>BEST SELLERS</h2>
    <hr>
    
   
    
    <div class="owl-carousel owl-theme">
    
        
    <?php
        // echo'<pre>';
        // print_r($this->dataView['list-prod']);   
        // echo'</pre>'; 
        
        foreach ($this->dataView['list-prod'] as $row ) {
            $price  = number_format($row['price']);
            echo "<div class='items' >";
                

                echo "<a href='' class='avt' >" . '<img src="Public/files/products/' . $row['uid'] . ".webp".'"/>' . '</a>';
                
                echo "<p class='gia'>" ."$".$price . '</p>';
                echo "<a href='index.php?ct=products&act=add-cart&id={$row['uid']}'><div  class='addToC'>" . "add to cart" . '</div></a>';
            

                echo "<div class='options'>";  
                    echo "<p>" . $row['name'] . '</p>';
                    
                echo "</div>";
            

            
            echo "</div>";
    }?>
      
    

        
    </div>
    <!-- <button id="shopnow" type =>
                    SHOP NOW!
    </button> -->
    <a href="<?php echo base_path ?>?ct=products&act=list-all">
        <input type="submit" value=" SHOP NOW!" id="shopnow" >
    </a>

</div>



<div class="contact">
    <h2>follow<br>
    one hundred devers on facebook
    <br>
    <a href="https://www.facebook.com/duckhue01">/one hundered devers</a>
    </h2>
   
   
   <div class="contact-img">
        <div class="contactItem">
            <img src="Public/img/contact_02.png" alt="" class="baner">
            <p>
                /ducckhue01 #100devers @duckhue01
                <br>one hundred devers store with luv
                 
            </p> 
        </div>
        <div class="contactItem">
            <img src="Public/img/contact_03.png" alt="" class="baner">
            <p>
                /ducckhue01 #100devers @duckhue01
                <br>one hundred devers store with luv
                 
            </p> 
        </div>
        <div class="contactItem">
            <img src="Public/img/contact_04.png" alt="" class="baner">
            <p>
                /ducckhue01 #100devers @duckhue01
                <br>one hundred devers store with luv
                 
            </p> 
        </div>
        <div class="contactItem">
            <img src="Public/img/contact_05.png" alt="" class="baner">
            <p>
                /ducckhue01 #100devers @duckhue01
                <br>one hundred devers store with luv
                 
            </p> 
        </div>
        <div class="contactItem">
            <img src="Public/img/contact_06.png" alt="" class="baner">
            <p>
                /ducckhue01 #100devers @duckhue01
                <br>one hundred devers store with luv
                 
            </p> 
        </div>
        

   </div>
  
    <img src="Public/img/text.png" alt="" id="text">


</div>

    <script>
        $(document).ready(function(){
            $(".owl-carousel").owlCarousel({
                        loop:true,
                        margin:10,
                        nav:true,
                      
                        
                       
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:3
                            },
                            1000:{
                                items:5
                            }
                        },
                        navText: [
                        '<svg width=20 height="20" viewBox="0 0 24 24"><path d="M16.67 0l2.83 2.829-9.339 9.175 9.339 9.167-2.83 2.829-12.17-11.996z"/></svg>',
                        '<svg width="20" height="20" viewBox="0 0 24 24"><path d="M5 3l3.057-3 11.943 12-11.943 12-3.057-3 9-9z"/></svg>'
                        ]
  
                    });
            });


    </script>


</body>

</html>