<script src="https://kit.fontawesome.com/d6818a8498.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="Public/css/login.css">

<div>
        
</div>
<section class="container01">

        <div class="container-login">
            <a id="exit" href='<?php echo base_path?>'><i class="fas fa-times"></i></a>
       
            <div class="form sign-in-form">
            
                <div class="wrapper">
                    <form action="" method="post">
                        <h1>Sign up</h1>
                        <p>Please, provide all the correct info to create an account</p>
                        <input type="text" placeholder="Full Name">
                        <input type="email" placeholder="Email">
                        <input type="password" placeholder="password">
                        <button type="submit">Sign Up</button>
                    </form>
                    
                </div>
            </div>
            <div class="form sign-up-form active">
                <div class="wrapper">
                    <form action="<?php echo base_path?>?act=login" method="post">
                        <h1>Sign In</h1>
                        <p>use your email and password to sign in</p>
                        <input type="text" placeholder="User Name" name="uname">
                        <input type="password" placeholder="Password" name="pwd">
                        
                        <button type="submit" id="signin">Sign In</button>
                        
                        <div class="memo">
                            <?php
                                $this ->showContent();
                            ?>
                            <p>
                                <?php   
                                    if (!empty($this->dataView['err'])) {
                                        echo '<p class="err">'. implode('<br>', $this->dataView['err']) . '</p>';
                                    }
                                    if (!empty($this->dataview['msg'])) {
                                        echo '<p class="msg">'. implode('<br>', $this->dataView['msg']) . '</p>';
                                    }
                                ?>
                                                
                            </p>
                        
                        </div>
                        
                        
                    </form>
                    
                </div>
            </div>
            <div class="overlay-container-login">
            <div class="overlay">
                <div class="overlay-left">
                    <h1>Create Account</h1>
                    <p>or</p>
                    <button id="signInButton">Log In</button>
                </div>
                <div class="overlay-right">
                    <h1>Please, Log In</h1>
                    <p>or</p>
                    <button id="signUpButton">Create Account</button>
                </div>
            </div>
            </div>
            <div class="bottom-text">
        <h2>Made with ❤ by one duckhue01 <a href="https://www.facebook.com/duckhue01" target="_blank">one hundered incognitos</a></h2>
        </div>
        </div>       
</section>

<script src="Public/js/login.js"></script> 

