<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    
    <title>Layout public</title>
</head>
<body>
    <h1>layout back</h1>
    <hr>
    <h3>content</h3>
    <?php
        $this ->showContent();
    ?>
    <table id="myTable">

    
    
    </table>


    <hr>
    <h2>footer</h2>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        });
    </script>


    <!-- <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
</body>
</html>