<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Layout public</title>
    <style type="text/css">
        @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Roboto:wght@300;500&display=swap");
            *{
                font-family: "Montserrat";
                padding:0;
                margin:0;
            }
            a{
                text-decoration: none;
                color: rgb(31, 92, 51);
                border: 1px solid black;
                margin: 10px
            }
            .option-bar{
                border: 1px solid black;
                text-align: center;

            }
        
            .name01{
                font-family: "Montserrat";
                color:rgb(31, 92, 51);
                border: 1px solid black;
                text-align: center;
            }
            .list-prod li{
                list-style: none;
                display: inline-block;
                width:200px;
                border: 1px solid #ccc;
                margin: 10px
            }
            .node-bar{
                border: 1px solid black;

            }

    </style>


</head>
<body>
    <!-- phan dau trang -->
    <h1 class="name01">100 incognitos store</h1>
    <div class="node-bar">
        <?php
            //phan hien thi so luong trong gio hang

            if (!empty($_SESSION['cart'])) {
                        
                // echo "<a href='". base_path . "?ct=products&act=view-cart >'" . "Cart(" . count($_SESSION['cart']) . ")" . "</a>";
                echo "<a href='" . base_path . "?ct=products&act=view-cart'>". "Cart(" . count($_SESSION['cart']) . ")"  ."</a>";


            }
                
            // chao
            if (!empty($_SESSION['auth'])) {

                echo "Xin Chaof ". $_SESSION['auth']['username'];
                echo "<br><a href='" . base_path . "?act=logout'>thoat</a>";

            }else{
                echo "<br><a href='" . base_path . "?act=login'>Log In</a>";
            }
        
        ?>

    </div>
    
    <div class="option-bar">       
        <a href="<?php echo base_path ?>?ct=products&act=list-all">Shop All</a>

        <a href="<?php echo base_path ?>">Home</a>
    
    
    </div>

    <hr>
    // content
    <?php
        $this ->showContent();
    ?>

    <hr>
    <h2>footer</h2>
</body>
</html>