
<!DOCTYPE html>
<html lang="en">

<head>
  <style>

    @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Roboto:wght@300;500&display=swap");
    *{
        font-family: "Montserrat";
        padding:0;
        margin:0;
      
        
    }

    .container-bg{
      width:100%;
    }
   .left-tmp{
     width:16%;
     background-color:rgb(160, 163, 161);
     /* height:190vh; */
     float:left;
     display:block;
     position:relative;
     top:0px;
     left:0px;
     box-shadow: 0 0 2px black;

   }
   .right-tmp{
     width:84%;
     

     
    
   }
   .tit h4{
     margin:30px 0 20px 20px;
   }
   .tit{
     width:100%;
     height:10vh;
     
   }
   hr{
      width:90%;
      position:absolute;
      top:70px;
      height:2px;
      border: none;
      height: 2px;
      left:5%;
      
      color: #333; /* old IE */
      background-color: #333; /* Modern Browsers */
   }
   .dashb a{
     color: black;
     margin:40px;
   }
  
  
  </style>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>100 Dever - Dashboard</title>

  <!-- Custom fonts for this template-->
  <script src="https://kit.fontawesome.com/d6818a8498.js" crossorigin="anonymous"></script>
  <!-- <link href="View/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
    <link href="View/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">

</head>
<body>
  

<div class="container-bg">
  <div class="left-tmp">
      <div class="tit">
        <h4>100 dever store</h4>
      </div>
      <hr>
      <div class="options">
        <div class="dashb">
            <a href="<?php echo base_path ?>?ct=admin&act=index">dash board</a>
        </div>
        <div class="dashb">
            <a href="<?php echo base_path ?>?ct=admin&act=prod">san pham</a>
        </div>
        <div class="dashb">
            <a href="<?php echo base_path ?>?ct=admin&act=staff">nhan vien</a>
        </div>
        <div class="dashb">
            <a href="<?php echo base_path ?>?ct=admin&act=order">don hang</a>
        </div>


      </div>


    </div>
    <div class="right-tmp">    
      <?php
            $this ->showContent();
        ?>
  </div>



</div>


  
      

  



  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

</body>

</html>
